# 一、Python 的基本数据类型 

## 1、整数

Python 可以处理任意大小的整数，当然包括负整数，在 Python 程序中，整数的表示方法和数学上的写法一模一样，例如：`1`，`100`，`-8080`，`0`，等等。

计算机由于使用二进制，所以，有时候用十六进制表示整数比较方便，十六进制用 0x 前缀和 0-9，a-f 表示，例如：0xff00，0xa5b4c3d2，等等。


## 2、浮点数 

浮点数也就是小数，之所以称为浮点数，是因为按照科学记数法表示时，一个浮点数的小数点位置是可变的。整数和浮点数在计算机内部存储的方式是不同的，整数运算永远是精确的（除法也是精确的），而浮点数运算则可能会有四舍五入的误差。

## 3、字符串 

字符串是以 '' 或 "" 括起来的任意文本，比如 `'abc'` ，`"123"` 等等。请注意，'' 或 "" 本身只是一种表示方式，不是字符串的一部分，因此，字符串 `'abc'` 只有 a，b，c 这 3 个字符。这个其他的编程语言也是类似的。

## 4、布尔值

布尔值和布尔代数的表示完全一致，一个布尔值只有 `True` 、 `False `两种值，要么是 `True`，要么是 `False`，在 Python 中，可以直接用 True、False 表示布尔值（请注意大小写），也可以通过布尔运算计算出来。

布尔值可以用 `and`、`or` 和 `not` 运算。

`and` 运算是与运算，只有所有都为 True，and 运算结果才是 True。

`or` 运算是或运算，只要其中有一个为 True，or 运算结果就是 True。

`not` 运算是非运算，它是一个单目运算符，把 True 变成 False，False 变成 True。


## 5、空值

基本上每种编程语言都有自己的特殊值——空值，在 Python 中，用 None 来表示

# 二、Python中的变量
## 1、变量的创建和赋值
在 Python 程序中，变量是用一个变量名表示，可以是任意数据类型，变量名必须是大小写英文、数字和下划线（_）的组合，且不能用数字开头，比如：

In [59]:
a = 88

In [60]:
a

88

In [61]:
type(a)

int

这里的 a 就是一个变量，代表一个整数，注意一点是 Python 是不用声明数据类型的。在 Python 中 = 是赋值语句，跟其他的编程语言也是一样的，因为 Python 定义变量时不需要声明数据类型，因此可以把任意的数据类型赋值给变量，且同一个变量可以反复赋值，而且可以是不同的数据类型。

In [62]:
a = 'Hello,World'

In [63]:
a

'Hello,World'

In [64]:
type(a)      #查看变量类型的

str

# 三、List（列表）

Python 内置的一种数据类型是列表：list。 list 是一种有序的集合，可以随时添加和删除其中的元素。

## 1、创建 List（列表）

创建一个列表，只要把逗号分隔的不同的数据项使用方括号括起来即可,且列表的数据项不需要具有相同的类型

In [65]:
list1=['两点水','twowter','liangdianshui',123]

## 2、访问 List（列表）中的值
使用下标索引来访问列表中的值，同样你也可以使用方括号的形式截取字符


In [66]:
list1[2]     # 通过索引来访问列表

'liangdianshui'

In [67]:
list1[0:2]      # 通过方括号的形式来截取列表中的数据

['两点水', 'twowter']

## 3、更新 List（列表）
可以通过索引对列表的数据项进行修改或更新，也可以使用 append() 方法来添加列表项。

In [68]:
list1

['两点水', 'twowter', 'liangdianshui', 123]

In [69]:
list1[2]=456    # 通过索引对列表的数据项进行修改或更新

In [70]:
list1

['两点水', 'twowter', 456, 123]

In [71]:
list1.append('hello')  # 使用 append() 方法来添加列表项

In [72]:
list1

['两点水', 'twowter', 456, 123, 'hello']

## 4、删除 List（列表）
使用 del 语句来删除列表的的元素

In [73]:
list1

['两点水', 'twowter', 456, 123, 'hello']

In [74]:
del list1[3]

In [75]:
list1

['两点水', 'twowter', 456, 'hello']

## 5、List（列表）运算符
列表对 + 和 * 的操作符与字符串相似。+ 号用于组合列表，* 号用于重复列表。    

|Python 表达式|结果|描述|
|-----------|-----|-----|
|len([1, 2, 3])|3|计算元素个数|
|[1, 2, 3] + [4, 5, 6]|	[1, 2, 3, 4, 5, 6]|	组合|
|['Hi!'] * 4|['Hi!', 'Hi!', 'Hi!', 'Hi!']|复制|
|3 in [1, 2, 3]|True|元素是否存在于列表中|
|for x in [1, 2, 3]: print x,|1 2 3|迭代|

## 6、List （列表）函数&方法

|函数&方法|描述|
|----|----|
|len(list)|列表元素个数|
|max(list)|返回列表元素最大值|
|min(list)|返回列表元素最小值|
|list(seq)|将元组转换为列表|
|list.append(obj)|在列表末尾添加新的对象|
|list.count(obj)|统计某个元素在列表中出现的次数|
|list.extend(seq)|在列表末尾一次性追加另一个序列中的多个值（用新列表扩展原来的列表）|
|list.index(obj)|从列表中找出某个值第一个匹配项的索引位置|
|list.insert(index, obj)|将对象插入列表|
|list.pop(obj=list[-1])|移除列表中的一个元素（默认最后一个元素），并且返回该元素的值|
|list.reverse()|反向列表中元素|
|list.sort([func])|对原列表进行排序|

# 四、元组
另一种有序列表叫元组：tuple 。tuple 和 list 非常类似，但是 tuple 一旦初始化就不能修改。那么不能修改是指什么意思呢？

tuple 不可变是指当你创建了 tuple 时候，它就不能改变了，也就是说它也没有 append()，insert() 这样的方法，但它也有获取某个索引值的方法，但是不能赋值。那么为什么要有 tuple 呢？那是因为 tuple 是不可变的，所以代码更安全。所以建议能用 tuple 代替 list 就尽量用 tuple 。    
其用法和列表大致相同。

In [76]:
tuple1=('张三','twowter',123,456)

In [77]:
tuple1

('张三', 'twowter', 123, 456)

# 五、字典
字典是另一种可变容器模型，且可存储任意类型对象。

字典的每个键值(key=>value)对用冒号(:)分割，每个对之间用逗号(,)分割，整个字典包括在花括号({})中 ,格式如下所示：
``` python
dict = {key1 : value1, key2 : value2 }
```

In [78]:
dict = {'zhangsan': 89,'lisi':'你好'}

注意：键必须是唯一的，但值则不必。值可以取任何数据类型，但键必须是不可变的。

In [79]:
dict

{'zhangsan': 89, 'lisi': '你好'}

In [80]:
dict['zhangsan']

89

这里需要注意的一点是：如果字典中没有这个键，是会报错的。

In [81]:
dict['zhangsan'] = 100      #字典的修改

In [82]:
dict['wangwu'] = 'yuwen'    #字典的新增

In [83]:
dict

{'zhangsan': 100, 'lisi': '你好', 'wangwu': 'yuwen'}

In [84]:
del dict['wangwu']    #根据字典的中的Key删除对应元素

In [85]:
dict

{'zhangsan': 100, 'lisi': '你好'}

In [86]:
dict.clear()    #删除字典中的所有元素

In [87]:
dict

{}

dict （字典） 的函数和方法

|方法和函数|描述|
|---------|--------|
|len(dict)|计算字典元素个数|
|str(dict)|输出字典可打印的字符串表示|
|type(variable)|返回输入的变量类型，如果变量是字典就返回字典类型|
|dict.clear()|删除字典内所有元素|
|dict.copy()|返回一个字典的浅复制|
|dict.values()|以列表返回字典中的所有值|
|dict.items()|以列表返回可遍历的(键, 值) 元组数组|

# 六、set集合
python 的 set 和其他语言类似, 是一个无序不重复元素集, 基本功能包括关系测试和消除重复元素。set 和 dict 类似，但是 set 不存储 value 值的。

## 1、set 的创建

创建一个 set，需要提供一个 list 作为输入集合

In [88]:
set1=set([123,456,789])

In [89]:
set1

{123, 456, 789}

传入的参数 `[123,456,789]` 是一个 list，而显示的 `{456, 123, 789}` 只是告诉你这个 set 内部有 456, 123, 789 这 3 个元素，显示的顺序跟你参数中的 list 里的元素的顺序是不一致的，这也说明了 set 是无序的。

还有一点，我们观察到输出的结果是在大括号中的，经过之前的学习，可以知道，tuple (元组) 使用小括号，list (列表) 使用方括号, dict (字典) 使用的是大括号，dict 也是无序的，只不过 dict 保存的是 key-value 键值对值，而 set 可以理解为只保存 key 值。

回忆一下，在 dict （字典） 中创建时，有重复的 key ，会被后面的 key-value 值覆盖的，而 重复元素在 set 中自动被过滤的。

In [90]:
set1=set([123,456,789,123,123])

In [91]:
set1

{123, 456, 789}

## 2、set 添加元素

In [92]:
set1=set([123,456,789])

In [93]:
set1

{123, 456, 789}

In [94]:
set1.add(100)     # 通过 add(key) 方法可以添加元素到 set 中，可以重复添加，但不会有效果

In [95]:
set1

{100, 123, 456, 789}

## 3、set 删除元素
通过 remove(key) 方法可以删除 set 中的元素


In [96]:
set1

{100, 123, 456, 789}

In [97]:
set1.remove(456)

In [98]:
set1

{100, 123, 789}

## 4、set 的运用
因为 set 是一个无序不重复元素集，因此，两个 set 可以做数学意义上的 union(并集), intersection(交集), difference(差集) 等操作。

![set集合运算](http://upload-images.jianshu.io/upload_images/2136918-733b1d1071f772bd?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

In [99]:
set1=set('hello')
set2=set(['p','y','y','h','o','n'])

In [100]:
set3=set1 & set2   # 交集 (求两个 set 集合中相同的元素)

In [101]:
set3

{'h', 'o'}

In [102]:
set4=set1 | set2    # 并集 （合并两个 set 集合的元素并去除重复的值）

In [103]:
set4

{'e', 'h', 'l', 'n', 'o', 'p', 'y'}

In [104]:
set5=set1 - set2    # 差集

In [105]:
set5

{'e', 'l'}

In [106]:
list1 = [111,222,333,444,111,222,333,444,555,666]  # 去除海量列表里重复元素，用 set 解决还是很不错的

In [107]:
set(list1)

{111, 222, 333, 444, 555, 666}